apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-myapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: ip-name
        image: kryptoninja/ipimg
        ports:
        - containerPort: 3000
